apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ingress
spec:
  rules:
    - host: ${LC_APP}.example.com
      http:
        paths:
          - path: /status
            pathType: Prefix
            backend:
              service:
                name: ${LC_APP}
                port:
                  number: ${LC_PORT}
